### ISSUE TITLE
Random pipeline generator for Halide

### ISSUE THREAD

**Issue by LucasBoTang** [facebookresearch/neural-rewriter#1]
I feel confusing about the Halide dateset. Where can I get the Random pipeline generator?
Thanks!

**Comment by Jungyhuk** [comment]
There is a typo in the README, thus the link to the random pipeline generator does not show up. We use the random pipeline generator listed [here](https://github.com/halide/Halide/tree/new_autoschedule_with_new_simplifier/apps/random_pipeline ). And I also updated the README to include the link in [this repo](https://github.com/Jungyhuk/neural-rewriter).

**Comment by LucasBoTang** [comment]
Thanks! Would you mind to provide a little instructions about running the random pipeline generator?

**Comment by Jungyhuk** [comment]
The dataset was generated by running the script [here](https://github.com/halide/Halide/blob/new_autoschedule_with_new_simplifier/apps/random_pipeline/bench_100.sh), and you can change the value of $PIPELINES and/or $SCHEDULES to generate as many samples as you want.

**Comment by LucasBoTang** [comment]
Thanks! You helped me a lot!
