### ISSUE TITLE
JSP data name on generator and load are unmatched

### ISSUE THREAD

**Issue by LucasBoTang** [facebookresearch/neural-rewriter#2]
For data generator, there is "jsp_r20"
`argParser.add_argument('--res_file', type=str, default='../data/jsp/jsp_r20_short_job.json')
argParser.add_argument('--res_train_file', type=str, default='../data/jsp/jsp_r20_train_short_job.json')
argParser.add_argument('--res_val_file', type=str, default='../data/jsp/jsp_r20_val_short_job.json')
argParser.add_argument('--res_test_file', type=str, default='../data/jsp/jsp_r20_test_short_job.json')`

For data loader, there is "jsp_r10"
`	elif title == 'jsp':
		data_group.add_argument('--train_dataset', type=str, default='../data/jsp/jsp_r10_train.json')
		data_group.add_argument('--val_dataset', type=str, default='../data/jsp/jsp_r10_val.json')
		data_group.add_argument('--test_dataset', type=str, default='../data/jsp/jsp_r10_test.json')`

**Comment by Jungyhuk** [comment]
In the sub-string "rX", X means the number of resource types, which should match the value of the command "--num_res". To make things clearer, I updated the default command values in [this repo](https://github.com/Jungyhuk/neural-rewriter).

**Comment by LucasBoTang** [comment]
Thank you so much!
